## 1. Import Libraries

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy

## 2. Import Data

In [2]:
# Creating path string to folder
path = r'C:\Users\Admin\Desktop\Instacart Basket Analysis'

In [3]:
# Importing test_customer_sample df from csv
test_customer = pd.read_csv(os.path.join(path, '02 Data', 'Prepared Data', 'test_customer.csv'))

In [4]:
# Check shape of df
test_customer.shape

(1000000, 33)

In [5]:
# Check head of df
test_customer.head()

,Unnamed: 0,Unnamed: 0.1,order_id,user_id,order_number,orders_day_of_week,hour_order_placed,days_since_prior_order,product_id,add_to_cart_order,...,Gender,State,Age,date_joined,no_of_dependents,fam_status,income,Region,low_activity_flag,meat_eater
0,0,0,2539329,1,1,2,8,NaN,196,1.0,...,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer,NaN
1,1,1,2398795,1,2,3,7,15.0,196,1.0,...,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer,NaN
2,2,2,473747,1,3,3,12,21.0,196,1.0,...,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer,NaN
3,3,3,2254736,1,4,4,7,29.0,196,1.0,...,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer,NaN
4,4,4,431534,1,5,4,15,28.0,196,1.0,...,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer,NaN

In [7]:
# Drop unneceaary columns
test_customer.drop(columns = ['Unnamed: 0','Unnamed: 0.1','meat_eater'])

,order_id,user_id,order_number,orders_day_of_week,hour_order_placed,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,frequency_flag,Gender,State,Age,date_joined,no_of_dependents,fam_status,income,Region,low_activity_flag
0,2539329,1,1,2,8,NaN,196,1.0,0,Soda,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer
1,2398795,1,2,3,7,15.0,196,1.0,1,Soda,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer
2,473747,1,3,3,12,21.0,196,1.0,1,Soda,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer
3,2254736,1,4,4,7,29.0,196,1.0,1,Soda,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer
4,431534,1,5,4,15,28.0,196,1.0,1,Soda,...,Non-frequent customer,Female,Alabama,31,2/17/2019,3,married,40423,South,Active customer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,1301146,26740,10,0,7,3.0,27336,7.0,1,Organic Rainbow Carrots,...,Regular customer,Male,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer
999996,945733,26740,7,6,9,7.0,13780,4.0,0,Thyme,...,Regular customer,Male,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer
999997,1301146,26740,10,0,7,3.0,13780,9.0,1,Thyme,...,Regular customer,Male,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer
999998,1301146,26740,10,0,7,3.0,37107,13.0,0,Ground Cumin,...,Regular customer,Male,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer
999999,1301146,26740,10,0,7,3.0,37119,14.0,0,Uncured Pepperoni,...,Regular customer,Male,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer

In [ ]:
# Drop unnecessary columns
test_customer = test_customer.drop(columns = ['Unnamed: 0','Unnamed: 0.1','meat_eater'])

## 3. Create Customer Profiles

### Create Demographic Profile - age, family status and number of dependents

In [57]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Young Individual without Kids'
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'single') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Young Individual without Kids'

In [58]:
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'divorced/widowed') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Young Individual without Kids'

In [59]:
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'living with parents and siblings') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Young Individual without Kids'

In [60]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Young Individual with Kids'
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'single') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Young Individual with Kids'

In [61]:
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'divorced/widowed') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Young Individual with Kids'

In [62]:
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'living with parents and siblings') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Young Individual with Kids'

In [64]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Young Married without Kids'
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'married') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Young Married without Kids'

In [65]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Young Married with Kids'
test_customer.loc[(test_customer['Age'] < 35) & (test_customer['fam_status'] == 'married') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Young Married with Kids'

In [66]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Middle Aged Individual without Kids'
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'single') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Middle Aged Individual without Kids'

In [67]:
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'divorced/widowed') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Middle Aged Individual without Kids'

In [68]:
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'living with parents and siblings') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Middle Aged Individual without Kids'

In [69]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Middle Aged Individual with Kids'
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'single') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Middle Aged Individual with Kids'

In [70]:
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'divorced/widowed') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Middle Aged Individual with Kids'

In [71]:
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'living with parents and siblings') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Middle Aged Individual with Kids'

In [72]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Middle Aged Married without Kids'
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'married') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Middle Aged Married without Kids'

In [84]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Middle Aged Married with Kids'
test_customer.loc[(test_customer['Age'] >= 35) & (test_customer['Age'] < 60) & (test_customer['fam_status'] == 'married') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Middle Aged Married with Kids'

In [74]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Older Individual without Kids'
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'single') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Older Individual without Kids'

In [75]:
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'divorced/widowed') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Older Individual without Kids'

In [83]:
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'living with parents and siblings') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Older Individual without Kids'

In [77]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Older Individual with Kids'
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'single') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Older Individual with Kids'

In [78]:
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'divorced/widowed') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Older Individual with Kids'

In [79]:
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'living with parents and siblings') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Older Individual with Kids'

In [80]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Older Married without Kids'
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'married') & (test_customer['no_of_dependents'] == 0), 'customer_profile'] = 'Older Married without Kids'

In [81]:
# Use loc() function to create customer profile flag based on age, family status and number of dependents - 'Older Married with Kids'
test_customer.loc[(test_customer['Age'] >= 60) & (test_customer['fam_status'] == 'married') & (test_customer['no_of_dependents'] > 0), 'customer_profile'] = 'Older Married with Kids'

In [85]:
test_customer['customer_profile'].value_counts(dropna = False)

Middle Aged Married with Kids          293768
Older Married with Kids                260934
Young Married with Kids                152556
Middle Aged Individual without Kids     91142
Older Individual without Kids           88574
Young Individual without Kids           67813
Young Individual with Kids              45213
Name: customer_profile, dtype: int64

### Create Diet/Purchasing Profile - based on department id's

In [86]:
# Create loop to create new object 'result' based on department id's

result = []

for value in test_customer['department_id']:
    if value == 12:
        result.append('Meat Eater')
    elif value == 8:
        result.append('Pet Owner')
    elif value == 5:
        result.append('Alcohol Drinker')
    else:
        result.append('No Profile')

In [87]:
# Assign result to new column
test_customer['Department Profile'] = result

In [88]:
# Frequency check new column
test_customer['Department Profile'].value_counts(dropna = False)

No Profile         981061
Meat Eater          13743
Alcohol Drinker      4958
Pet Owner             238
Name: Department Profile, dtype: int64

In [92]:
# Create subset of 'Pet Owner'
test_customer_pet_owner = test_customer.loc[test_customer['Department Profile'] == 'Pet Owner']

In [93]:
# visualise df
test_customer_pet_owner.head(30)

,order_id,user_id,order_number,orders_day_of_week,hour_order_placed,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,State,Age,date_joined,no_of_dependents,fam_status,income,Region,low_activity_flag,customer_profile,Department Profile
27462,1358735,11363,10,0,10,19.0,35956,6.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,South Carolina,65,5/29/2019,2,married,152595,South,Active customer,Older Married with Kids,Pet Owner
40043,1173846,17528,1,0,17,NaN,7076,16.0,0,Grain Free Chicken Formula Cat Food,...,Michigan,54,11/8/2017,2,married,102630,Midwest,Active customer,Middle Aged Married with Kids,Pet Owner
40044,1645810,17528,4,2,15,21.0,7076,4.0,1,Grain Free Chicken Formula Cat Food,...,Michigan,54,11/8/2017,2,married,102630,Midwest,Active customer,Middle Aged Married with Kids,Pet Owner
76968,2269382,35095,28,4,11,4.0,35956,4.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Connecticut,74,6/10/2018,3,married,117313,Northeast,Active customer,Older Married with Kids,Pet Owner
133376,1382805,60134,17,5,10,5.0,35956,13.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,California,29,5/31/2018,2,married,82000,West,Active customer,Young Married with Kids,Pet Owner
191240,1774907,87688,33,5,13,3.0,10863,17.0,0,Grain Free Turkey & Salmon Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191241,372708,87688,35,0,15,8.0,10863,27.0,1,Grain Free Turkey & Salmon Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191242,17213,87688,37,5,13,11.0,10863,22.0,1,Grain Free Turkey & Salmon Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191243,24383,87688,41,5,13,6.0,10863,15.0,1,Grain Free Turkey & Salmon Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191244,1774907,87688,33,5,13,3.0,17766,18.0,0,Grain Free Turkey Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191245,372708,87688,35,0,15,8.0,17766,25.0,1,Grain Free Turkey Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191246,17213,87688,37,5,13,11.0,17766,24.0,1,Grain Free Turkey Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191247,24383,87688,41,5,13,6.0,17766,13.0,1,Grain Free Turkey Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191248,1774907,87688,33,5,13,3.0,7076,19.0,0,Grain Free Chicken Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191249,372708,87688,35,0,15,8.0,7076,23.0,1,Grain Free Chicken Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191250,17213,87688,37,5,13,11.0,7076,21.0,1,Grain Free Chicken Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191251,24383,87688,41,5,13,6.0,7076,12.0,1,Grain Free Chicken Formula Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191252,1774907,87688,33,5,13,3.0,28134,20.0,0,Grain Free Turkey Canned Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191444,1774907,87688,33,5,13,3.0,35956,15.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191445,372708,87688,35,0,15,8.0,35956,26.0,1,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
191446,17213,87688,37,5,13,11.0,35956,23.0,1,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Louisiana,75,2/28/2019,3,married,84956,South,Active customer,Older Married with Kids,Pet Owner
198628,1473712,91001,1,3,18,NaN,35956,5.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Kansas,32,1/6/2018,1,married,90081,Midwest,Active customer,Young Married with Kids,Pet Owner
198629,1673524,91001,2,5,17,30.0,35956,2.0,1,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Kansas,32,1/6/2018,1,married,90081,Midwest,Active customer,Young Married with Kids,Pet Owner
198630,1058739,91001,4,2,12,30.0,35956,2.0,1,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Kansas,32,1/6/2018,1,married,90081,Midwest,Active customer,Young Married with Kids,Pet Owner
198631,1933132,91001,5,1,13,30.0,35956,2.0,1,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Kansas,32,1/6/2018,1,married,90081,Midwest,Active customer,Young Married with Kids,Pet Owner
226398,1940282,104415,13,4,15,8.0,35956,7.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Kentucky,20,3/14/2020,2,living with parents and siblings,50671,South,Active customer,Young Individual with Kids,Pet Owner
252090,1173084,115467,8,0,9,12.0,35956,15.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Arizona,56,8/15/2018,3,married,109719,West,Active customer,Middle Aged Married with Kids,Pet Owner
295047,2172950,135256,8,2,14,4.0,35956,9.0,0,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Arkansas,62,3/25/2019,1,married,122737,South,Active customer,Older Married with Kids,Pet Owner
295048,3154367,135256,34,4,18,8.0,35956,3.0,1,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Arkansas,62,3/25/2019,1,married,122737,South,Active customer,Older Married with Kids,Pet Owner
295049,2431695,135256,36,4,16,4.0,35956,5.0,1,Fancy Feast Wet Classic Chicken Feast Cat Food,...,Arkansas,62,3/25/2019,1,married,122737,South,Active customer,Older Married with Kids,Pet Owner

In [94]:
# Create dataframe
df_user_id = test_customer.loc[test_customer['user_id'].isin([1,26740])]

In [95]:
df_user_id.shape

(134, 32)

In [99]:
df_user_id.head(50)

,order_id,user_id,order_number,orders_day_of_week,hour_order_placed,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,State,Age,date_joined,no_of_dependents,fam_status,income,Region,low_activity_flag,customer_profile,Department Profile
0,2539329,1,1,2,8,NaN,196,1.0,0,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
1,2398795,1,2,3,7,15.0,196,1.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
2,473747,1,3,3,12,21.0,196,1.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
3,2254736,1,4,4,7,29.0,196,1.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
4,431534,1,5,4,15,28.0,196,1.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
5,3367565,1,6,2,7,19.0,196,1.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
6,550135,1,7,1,9,20.0,196,1.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
7,3108588,1,8,1,14,14.0,196,2.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
8,2295261,1,9,1,16,0.0,196,4.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
9,2550362,1,10,4,8,30.0,196,1.0,1,Soda,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
10,2539329,1,1,2,8,NaN,14084,2.0,0,Organic Unsweetened Vanilla Almond Milk,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
11,2539329,1,1,2,8,NaN,12427,3.0,0,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
12,2398795,1,2,3,7,15.0,12427,3.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
13,473747,1,3,3,12,21.0,12427,2.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
14,2254736,1,4,4,7,29.0,12427,2.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
15,431534,1,5,4,15,28.0,12427,2.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
16,3367565,1,6,2,7,19.0,12427,2.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
17,550135,1,7,1,9,20.0,12427,3.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
18,3108588,1,8,1,14,14.0,12427,1.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
19,2295261,1,9,1,16,0.0,12427,6.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
20,2550362,1,10,4,8,30.0,12427,9.0,1,Original Beef Jerky,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
21,2539329,1,1,2,8,NaN,26088,4.0,0,Aged White Cheddar Popcorn,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
22,2398795,1,2,3,7,15.0,26088,5.0,1,Aged White Cheddar Popcorn,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
23,2539329,1,1,2,8,NaN,26405,5.0,0,XL Pick-A-Size Paper Towel Rolls,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
24,2254736,1,4,4,7,29.0,26405,5.0,1,XL Pick-A-Size Paper Towel Rolls,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
25,2398795,1,2,3,7,15.0,10258,2.0,0,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
26,473747,1,3,3,12,21.0,10258,3.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
27,2254736,1,4,4,7,29.0,10258,3.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
28,431534,1,5,4,15,28.0,10258,3.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
29,3367565,1,6,2,7,19.0,10258,3.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
30,550135,1,7,1,9,20.0,10258,2.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
31,3108588,1,8,1,14,14.0,10258,3.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
32,2295261,1,9,1,16,0.0,10258,5.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
33,2550362,1,10,4,8,30.0,10258,6.0,1,Pistachios,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
34,2398795,1,2,3,7,15.0,13176,4.0,0,Bag of Organic Bananas,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
35,431534,1,5,4,15,28.0,13176,8.0,1,Bag of Organic Bananas,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
36,2398795,1,2,3,7,15.0,13032,6.0,0,Cinnamon Toast Crunch,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
37,550135,1,7,1,9,20.0,13032,5.0,1,Cinnamon Toast Crunch,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
38,2550362,1,10,4,8,30.0,13032,8.0,1,Cinnamon Toast Crunch,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
39,473747,1,3,3,12,21.0,25133,4.0,0,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
40,2254736,1,4,4,7,29.0,25133,4.0,1,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
41,431534,1,5,4,15,28.0,25133,4.0,1,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
42,3367565,1,6,2,7,19.0,25133,4.0,1,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
43,550135,1,7,1,9,20.0,25133,4.0,1,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
44,3108588,1,8,1,14,14.0,25133,4.0,1,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
45,2295261,1,9,1,16,0.0,25133,3.0,1,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
46,2550362,1,10,4,8,30.0,25133,5.0,1,Organic String Cheese,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
47,473747,1,3,3,12,21.0,30450,5.0,0,Creamy Almond Butter,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
48,431534,1,5,4,15,28.0,10326,5.0,0,Organic Fuji Apples,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile
49,431534,1,5,4,15,28.0,17122,6.0,0,Honeycrisp Apples,...,Alabama,31,2/17/2019,3,married,40423,South,Active customer,Young Married with Kids,No Profile

In [100]:
df_user_id.tail(50)

,order_id,user_id,order_number,orders_day_of_week,hour_order_placed,days_since_prior_order,product_id,add_to_cart_order,reordered,product_name,...,State,Age,date_joined,no_of_dependents,fam_status,income,Region,low_activity_flag,customer_profile,Department Profile
999950,2340439,26740,5,0,8,20.0,47209,6.0,1,Organic Hass Avocado,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999951,2652986,26740,3,2,7,30.0,38656,15.0,0,Gluten Free Peanut Butter Dark Chocolate Chewy...,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999952,2652986,26740,3,2,7,30.0,10305,16.0,0,Black Plum,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999953,1784178,26740,6,6,7,30.0,39877,6.0,0,Organic Granny Smith Apple,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999954,945733,26740,7,6,9,7.0,39877,2.0,1,Organic Granny Smith Apple,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999955,1185989,26740,8,2,15,30.0,39877,4.0,1,Organic Granny Smith Apple,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999956,2205025,26740,9,4,7,16.0,39877,2.0,1,Organic Granny Smith Apple,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999957,1556084,26740,1,0,13,NaN,39928,4.0,0,Organic Kiwi,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999958,1085636,26740,2,5,8,12.0,39928,2.0,1,Organic Kiwi,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999959,2652986,26740,3,2,7,30.0,39928,9.0,1,Organic Kiwi,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999960,1301146,26740,10,0,7,3.0,39928,10.0,1,Organic Kiwi,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999961,1556084,26740,1,0,13,NaN,21903,12.0,0,Organic Baby Spinach,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999962,1085636,26740,2,5,8,12.0,21903,11.0,1,Organic Baby Spinach,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999963,2340439,26740,5,0,8,20.0,21903,8.0,1,Organic Baby Spinach,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999964,1185989,26740,8,2,15,30.0,21903,9.0,1,Organic Baby Spinach,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999965,2652986,26740,3,2,7,30.0,21137,10.0,0,Organic Strawberries,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999966,1185989,26740,8,2,15,30.0,21137,13.0,1,Organic Strawberries,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999967,2205025,26740,9,4,7,16.0,21137,4.0,1,Organic Strawberries,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999968,1085636,26740,2,5,8,12.0,42265,6.0,0,Organic Baby Carrots,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999969,1085636,26740,2,5,8,12.0,11777,1.0,0,Red Raspberries,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999970,1085636,26740,2,5,8,12.0,31717,12.0,0,Organic Cilantro,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999971,2652986,26740,3,2,7,30.0,31717,17.0,1,Organic Cilantro,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999972,2340439,26740,5,0,8,20.0,31717,5.0,1,Organic Cilantro,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999973,945733,26740,7,6,9,7.0,31717,12.0,1,Organic Cilantro,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999974,1185989,26740,8,2,15,30.0,31717,3.0,1,Organic Cilantro,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999975,2205025,26740,9,4,7,16.0,20323,3.0,0,Strained Tomatoes,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999976,1556084,26740,1,0,13,NaN,43967,2.0,0,Raspberry Lemonade,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999977,1301146,26740,10,0,7,3.0,43967,11.0,1,Raspberry Lemonade,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999978,1556084,26740,1,0,13,NaN,31343,9.0,0,Shredded Mild Cheddar Cheese,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999979,2360451,26740,4,1,18,13.0,31343,6.0,1,Shredded Mild Cheddar Cheese,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999980,1556084,26740,1,0,13,NaN,15592,11.0,0,Organic Baby Romaine Lettuce,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999981,2652986,26740,3,2,7,30.0,15592,3.0,1,Organic Baby Romaine Lettuce,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999982,1784178,26740,6,6,7,30.0,15592,2.0,1,Organic Baby Romaine Lettuce,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999983,2360451,26740,4,1,18,13.0,44661,7.0,0,Bicolor Sweet Corn,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999984,2652986,26740,3,2,7,30.0,18531,11.0,0,Organic Heavy Whipping Cream,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999985,1556084,26740,1,0,13,NaN,15290,6.0,0,Orange Bell Pepper,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999986,1085636,26740,2,5,8,12.0,15290,9.0,1,Orange Bell Pepper,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999987,1185989,26740,8,2,15,30.0,15290,10.0,1,Orange Bell Pepper,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999988,1301146,26740,10,0,7,3.0,15290,3.0,1,Orange Bell Pepper,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999989,1301146,26740,10,0,7,3.0,31506,20.0,0,Extra Virgin Olive Oil,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999990,2652986,26740,3,2,7,30.0,13083,1.0,0,Lowfat Small Curd Cottage Cheese,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999991,1301146,26740,10,0,7,3.0,15261,22.0,0,Organic Rosemary,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999992,1301146,26740,10,0,7,3.0,27243,16.0,0,Premium Pure Cane Granulated Sugar,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999993,2340439,26740,5,0,8,20.0,27336,3.0,0,Organic Rainbow Carrots,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999994,1784178,26740,6,6,7,30.0,27336,3.0,1,Organic Rainbow Carrots,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999995,1301146,26740,10,0,7,3.0,27336,7.0,1,Organic Rainbow Carrots,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999996,945733,26740,7,6,9,7.0,13780,4.0,0,Thyme,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999997,1301146,26740,10,0,7,3.0,13780,9.0,1,Thyme,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999998,1301146,26740,10,0,7,3.0,37107,13.0,0,Ground Cumin,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile
999999,1301146,26740,10,0,7,3.0,37119,14.0,0,Uncured Pepperoni,...,Iowa,24,3/4/2020,1,married,41674,Midwest,Active customer,Young Married with Kids,No Profile